apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3-secrets
  namespace: loki
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: loki-s3-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "loki-minio-access"
